stages:
  - build
  - test
  - deploy

default:
  image: docker:23.0.3
#  services:
#    - docker:dind

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - cache/

build_job:
  stage: build
  only:
    - main
  variables:
#    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
    CI_REGISTRY: registry.aidar-sandbox.ru:5050
    CI_REGISTRY_IMAGE: registry.aidar-sandbox.ru:5050/skills/developer-skills-rating-client
  script:
    - echo "Running build"
    - echo "user=$CI_REGISTRY_USER token=$CI_JOB_TOKEN registry=$CI_REGISTRY"
#    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

# disabled
.test_job:
  stage: test
  only:
    - main
  script:
    - echo "Running tests"
    - docker run --name frontend-container -d frontend-image
    - docker exec frontend-container npm test --passWithNoTests
    - docker stop frontend-container
    - docker rm frontend-container

deploy_job:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying to Docker Swarm"
    - docker stack deploy --compose-file docker-compose-dev.yml frontend-skills-stack
