stages:
  - build
  - deploy

build:
  image: node:latest
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

deploy:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache kubectl
    - kubectl apply -f deployment.yaml
