stages:
  - build
  - test
  - deploy

default:
  image: docker:23.0.3
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
    CI_REGISTRY: http://registry.gitlab.aidar-sandbox.ru:5555
    CI_REGISTRY_IMAGE: registry.gitlab.aidar-sandbox.ru:5555/skills/developer-skills-rating-client

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - cache/

build_job:
  stage: build
#  before_script:
#    - apk add --no-cache git
#    - docker info
  script:
    - echo "Running build"
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

# disabled
.test_job:
  stage: test
  script:
    - echo "Running tests"
    - docker run --name frontend-container -d frontend-image
    - docker exec frontend-container npm test --passWithNoTests
    - docker stop frontend-container
    - docker rm frontend-container

deploy_job:
  stage: deploy
  before_script:
    - apk add --no-cache docker-compose
  script:
    - echo "Deploying to Docker Swarm"
    - docker stack deploy --compose-file docker-compose-dev.yml frontend-skills-stack
