stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t frontend-image .

test_job:
  stage: test
  script:
    - echo "Running tests"
    # Здесь можно добавить скрипты для запуска тестов

deploy_job:
  stage: deploy
  script:
    - echo "Deploying to server"
    # Здесь можно добавить скрипты для деплоя, например, на удаленный сервер или в облако

cache:
  paths:
    - /cache
