stages:
  - build
  - test
  - deploy

#variables:
#  DOCKER_HOST: tcp://localhost:2375
#  DOCKER_TLS_CERTDIR: ""
#  CI_REGISTRY: http://registry.gitlab.aidar-sandbox.ru:5555
#  CI_REGISTRY_IMAGE: registry.gitlab.aidar-sandbox.ru:5555/skills/developer-skills-rating-client

default:
  image: docker:23.0.3
  services:
    - docker:dind

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - cache/

build_job:
  stage: build
  only:
    - main
  script:
    - echo "Running build"
#    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin <<<$CI_JOB_TOKEN
#    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#    - docker login $CI_REGISTRY -u $CI_DEPLOY_USER --password-stdin <<<$CI_DEPLOY_PASSWORD
#    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin <<<$CI_REGISTRY_PASSWORD
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

# disabled
.test_job:
  stage: test
  only:
    - main
  script:
    - echo "Running tests"
    - docker run --name frontend-container -d frontend-image
    - docker exec frontend-container npm test --passWithNoTests
    - docker stop frontend-container
    - docker rm frontend-container

deploy_job:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying to Docker Swarm"
    - docker stack deploy --compose-file docker-compose-dev.yml frontend-skills-stack
