stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache git
    - docker info
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
    CI_REGISTRY_IMAGE: "127.0.0.1:8111/skills/developer-skills-rating-client"
  script:
    - echo "Running build"
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
#    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

# disabled
.test_job:
  stage: test
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "Running tests"
    - docker run --name frontend-container -d frontend-image
    - docker exec frontend-container npm test --passWithNoTests
    - docker stop frontend-container
    - docker rm frontend-container

deploy_job:
  stage: deploy
  script:
    - echo "Deploying to Docker Swarm"
    - docker stack deploy --compose-file docker-compose.yml frontend-skills-stack

cache:
  paths:
    - /cache
