stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    - docker build -t my-react-app .
#  tags:
#    - docker

deploy_job:
  stage: deploy
  script:
    - kubectl apply -f deployment.yml
  tags:
    - kubernetes
