stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build_job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

test_job:
  stage: test
  script:
    - echo "Running tests"
    # Здесь можно добавить скрипты для запуска тестов

deploy_job:
  stage: deploy
  script:
    - echo "Deploying to server"
    # Здесь можно добавить скрипты для деплоя, например, на удаленный сервер или в облако

cache:
  paths:
    - /cache
