version: '3.7'

services:
  frontend:
    image: ${CI_REGISTRY_IMAGE}
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure