# Base image for a lightweight React application
FROM node:lts-alpine as builder

# Set working directory inside the container
WORKDIR /app

# Copy package dependencies
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

# Copy application files into the container
COPY . .

RUN npm run build

# production environment
FROM nginx:stable-alpine

COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]