version: '3.7'

services:
  frontend:
    image: registry.gitlab.aidar-sandbox.ru:5555/skills/developer-skills-rating-client:latest
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure